name: Automated testing

on:
  # Whenever someone pushes to a branch in our repo
  push:
    branches:
      - "*"
  # Whenever a pull request is opened, reopened, or gets new commits.
  pull_requests:
# This implies that for every push to a local branch in our repo for which a
# pull request is open this runs twice. But it is important to ensure that pull
# requests get tested even if their branch comes from a fork.

jobs:
  l3build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install TeX Live
        uses: zauguin/install-texlive@v2
        with:
          # List the required TeX Live packages in a separate file to allow
          # reuse in different workflows.
          package_file: .github/tl_packages

      - name: Run l3build
        run: l3build ctan -q -H
